/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./components/HomePage/AboutView.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    Contact: typeof import('./components/HomePage/Contact.vue')['default']
    Education: typeof import('./components/HomePage/Education.vue')['default']
    Experience: typeof import('./components/HomePage/Experience.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    LottieAnimation: typeof import('vue3-lottie')['Vue3Lottie']
    MainVisual: typeof import('./components/HomePage/MainVisual.vue')['default']
    ProjectCard: typeof import('./components/HomePage/ProjectCard.vue')['default']
    Projects: typeof import('./components/HomePage/Projects.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skills: typeof import('./components/HomePage/Skills.vue')['default']
  }
}
